version: '3.4'

services:
  hellocontainers.api:
    image: ${DOCKER_REGISTRY-}hellocontainersapi
    build:
      context: ./HelloContainers.Api
      dockerfile: Dockerfile
    depends_on:
      - db
  hellocontainers.web:
    image: ${DOCKER_REGISTRY-}hellocontainersweb
    build:
      context: ./HelloContainers.Web
      dockerfile: Dockerfile
    depends_on:
      - hellocontainers.api
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sql-datavolume:/var/opt/mssql
volumes:
  sql-datavolume: